"""Write editors/vscode/syntaxes/q.tmLanguage.json, the q syntax colouring.

A TextMate grammar is how VS Code colours Python, and every other language
it ships: a set of regular expressions that tag spans of text with scope
names (`comment.line`, `string.quoted`, `support.function`, ...) which the
colour theme then paints. Like the linter, it reads the source and never runs
it.

The builtin names come from src/reserved.json, the list the rules already
use, so this is generated rather than written by hand:

    python3 scripts/q_grammar.py > editors/vscode/syntaxes/q.tmLanguage.json

`tests/q_grammar.rs` fails when the committed file is stale.

What it gets right is the lexical shape q shares with the linter's own views
in src/lib.rs: a `/` opens a comment only at the start of a line or after
whitespace, a line holding a lone `/` opens a block that a lone `\\` closes,
a lone `\\` outside a block ends the script, a line opening with `\\` is a
system command, and `p)` / `k)` lines are another language.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]

CONTROL = ["if", "do", "while"]
QSQL = ["select", "exec", "update", "delete", "from", "by", "where"]

# An identifier edge: not preceded or followed by a name character, a dot
# (so `.q.count` is not `count`) or a backtick (so `` `count `` is a symbol).
BEFORE = r"(?<![A-Za-z0-9_.`])"
AFTER = r"(?![A-Za-z0-9_])"
NAME = r"\.?[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z0-9_]+)*"


def words(names):
    return BEFORE + "(?:" + "|".join(sorted(names, key=lambda n: (-len(n), n))) + ")" + AFTER


def grammar():
    reserved = json.loads((ROOT / "src" / "reserved.json").read_text())
    builtins = [n for n in reserved if n not in CONTROL and n not in QSQL]
    missing = [n for n in CONTROL + QSQL if n not in reserved]
    assert not missing, f"not in reserved.json: {missing}"

    expression = [
        {"include": "#comment"},
        {"include": "#string"},
        {"include": "#symbol"},
        {"include": "#lambda"},
        {"include": "#number"},
        {"include": "#definition"},
        {"include": "#keyword"},
        {"include": "#system-namespace"},
        {"include": "#builtin"},
        {"include": "#name"},
        {"include": "#operator"},
    ]

    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "q",
        "scopeName": "source.q",
        "comment": "Generated by scripts/q_grammar.py from src/reserved.json - edit that, not this.",
        "patterns": [
            {"include": "#block-comment"},
            {"include": "#end-of-script"},
            {"include": "#foreign"},
            {"include": "#system-command"},
            {"include": "#prompt"},
            {"include": "#expression"},
        ],
        "repository": {
            "block-comment": {
                "name": "comment.block.q",
                "begin": r"^/\s*$",
                "end": r"^\\\s*$",
                "beginCaptures": {"0": {"name": "punctuation.definition.comment.begin.q"}},
                "endCaptures": {"0": {"name": "punctuation.definition.comment.end.q"}},
                "patterns": [{"include": "#qdoc"}],
            },
            "end-of-script": {
                "comment": "A lone backslash outside a block ends the script; q reads nothing after it.",
                "name": "comment.block.end-of-script.q",
                "begin": r"^\\\s*$",
                "end": r"(?=A)(?!A)",
                "beginCaptures": {"0": {"name": "punctuation.definition.comment.begin.q"}},
            },
            "foreign": {
                "comment": "p) and k) lines, and the indented lines that continue them.",
                "patterns": [
                    {
                        "name": "meta.embedded.block.python.q",
                        "begin": r"^(p\))",
                        "end": r"^(?=\S|\s*$)",
                        "beginCaptures": {"1": {"name": "keyword.other.language-prefix.q"}},
                        "contentName": "source.python",
                        "patterns": [{"include": "source.python"}],
                    },
                    {
                        "name": "meta.embedded.block.k.q",
                        "begin": r"^(k\))",
                        "end": r"^(?=\S|\s*$)",
                        "beginCaptures": {"1": {"name": "keyword.other.language-prefix.q"}},
                        "contentName": "string.unquoted.k.q",
                    },
                ],
            },
            "system-command": {
                "patterns": [
                    {
                        "match": r"^(\\d)\s+(\.[A-Za-z0-9_.]*)",
                        "captures": {
                            "1": {"name": "keyword.other.system.q"},
                            "2": {"name": "entity.name.namespace.q"},
                        },
                    },
                    {
                        "match": r"^(\\[A-Za-z_12]\w*|\\\\)(.*)$",
                        "captures": {
                            "1": {"name": "keyword.other.system.q"},
                            "2": {"name": "string.unquoted.argument.q"},
                        },
                    },
                ],
            },
            "prompt": {"match": r"^q\)", "name": "punctuation.separator.prompt.q"},
            "expression": {"patterns": expression},
            "comment": {
                "patterns": [
                    {
                        "comment": "qdoc: `///` opens a documentation block and `//` continues it.",
                        "name": "comment.line.documentation.q",
                        "begin": r"(?:^|(?<=\s))(//+)",
                        "end": r"$",
                        "beginCaptures": {"1": {"name": "punctuation.definition.comment.q"}},
                        "patterns": [{"include": "#qdoc"}],
                    },
                    {
                        "name": "comment.line.q",
                        "begin": r"(?:^|(?<=\s))(/)",
                        "end": r"$",
                        "beginCaptures": {"1": {"name": "punctuation.definition.comment.q"}},
                        "patterns": [{"include": "#qdoc"}],
                    },
                ],
            },
            "qdoc": {
                "patterns": [
                    {
                        "match": r"(@param)\s+([A-Za-z][A-Za-z0-9_]*)(?:\s+(\{[^}]*\}))?",
                        "captures": {
                            "1": {"name": "storage.type.class.qdoc.q"},
                            "2": {"name": "variable.parameter.qdoc.q"},
                            "3": {"name": "entity.name.type.qdoc.q"},
                        },
                    },
                    {
                        "match": r"(@[A-Za-z]+)(?:\s+(\{[^}]*\}))?",
                        "captures": {
                            "1": {"name": "storage.type.class.qdoc.q"},
                            "2": {"name": "entity.name.type.qdoc.q"},
                        },
                    },
                ],
            },
            "string": {
                "name": "string.quoted.double.q",
                "begin": '"',
                "end": '"',
                "beginCaptures": {"0": {"name": "punctuation.definition.string.begin.q"}},
                "endCaptures": {"0": {"name": "punctuation.definition.string.end.q"}},
                "patterns": [
                    {"match": r'\\(?:[0-7]{3}|[nrt"\\])', "name": "constant.character.escape.q"},
                    {"match": r"\\.", "name": "invalid.illegal.escape.q"},
                ],
            },
            "symbol": {
                "patterns": [
                    {
                        "comment": "A file or network handle: `:path/to/file, `:host:port.",
                        "match": r"`:[A-Za-z0-9_.:/\-]*",
                        "name": "constant.other.symbol.handle.q",
                    },
                    {"match": r"`[A-Za-z0-9_.:]*", "name": "constant.other.symbol.q"},
                ],
            },
            "lambda": {
                "name": "meta.function.lambda.q",
                "begin": r"(\{)\s*(?:(\[)([^\]]*)(\]))?",
                "end": r"\}",
                "beginCaptures": {
                    "1": {"name": "punctuation.section.function.begin.q"},
                    "2": {"name": "punctuation.definition.parameters.begin.q"},
                    "3": {
                        "patterns": [
                            {"match": r"[A-Za-z][A-Za-z0-9_]*", "name": "variable.parameter.q"},
                            {"match": ";", "name": "punctuation.separator.parameters.q"},
                        ]
                    },
                    "4": {"name": "punctuation.definition.parameters.end.q"},
                },
                "endCaptures": {"0": {"name": "punctuation.section.function.end.q"}},
                # A lone `/` or `\\` is read by the script loader line by line, so
                # it opens a block or ends the script inside a lambda too.
                "patterns": [{"include": "#block-comment"}, {"include": "#end-of-script"}]
                + expression[:6]
                + [
                    {
                        "comment": "x, y and z are a lambda's implicit parameters.",
                        "match": BEFORE + "[xyz]" + AFTER,
                        "name": "variable.language.implicit.q",
                    }
                ]
                + expression[6:],
            },
            "number": {
                "patterns": [
                    {
                        "name": "constant.numeric.temporal.q",
                        "match": BEFORE
                        + "(?:"
                        + "|".join(
                            [
                                # timestamp and datetime
                                r"\d{4}\.\d{2}\.\d{2}[DT](?:\d{2}(?::\d{2}(?::\d{2}(?:\.\d*)?)?)?)?[pz]?",
                                # month, date
                                r"\d{4}\.\d{2}(?:\.\d{2}d?|m)",
                                # timespan
                                r"\d+D(?:\d{2}(?::\d{2}(?::\d{2}(?:\.\d*)?)?)?)?n?",
                                # time, minute, second
                                r"\d{2}:\d{2}(?::\d{2}(?:\.\d{3})?)?[tuv]?",
                            ]
                        )
                        + ")"
                        + AFTER,
                    },
                    {
                        "name": "constant.language.null.q",
                        "match": BEFORE + r"-?0[NnWw][ghijefcspmdznuvt]?" + AFTER,
                    },
                    {"name": "constant.language.boolean.q", "match": BEFORE + r"[01]+b" + AFTER},
                    {"name": "constant.numeric.byte.q", "match": BEFORE + r"0x[0-9a-fA-F]*" + AFTER},
                    {
                        "name": "constant.numeric.q",
                        "match": BEFORE + r"(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?[hijefcnuvt]?" + AFTER,
                    },
                ],
            },
            "definition": {
                "patterns": [
                    {
                        "comment": "A name assigned a lambda: f:{...} or .ns.f::{...}.",
                        "match": BEFORE + "(" + NAME + r")\s*(::?)(?=\s*\{)",
                        "captures": {
                            "1": {"name": "entity.name.function.q"},
                            "2": {"name": "keyword.operator.assignment.q"},
                        },
                    },
                    {
                        "comment": "Any other assignment, a:1 or a::1, but not an iterator such as /: or \\:.",
                        "match": BEFORE + "(" + NAME + r")\s*(::?)(?![:/\\'])",
                        "captures": {
                            "1": {"name": "variable.other.definition.q"},
                            "2": {"name": "keyword.operator.assignment.q"},
                        },
                    },
                ],
            },
            "keyword": {
                "patterns": [
                    {"name": "keyword.control.q", "match": words(CONTROL)},
                    {"name": "keyword.control.conditional.q", "match": r"\$(?=\[)"},
                    {"name": "keyword.other.qsql.q", "match": words(QSQL)},
                ],
            },
            "system-namespace": {
                "comment": "The namespaces q reserves for itself: .q .Q .z .h .j .o and their members.",
                "name": "support.function.system.q",
                "match": BEFORE + r"\.[qQzhjo](?:\.[A-Za-z0-9_]+)*" + AFTER,
            },
            "builtin": {"name": "support.function.builtin.q", "match": words(builtins)},
            "name": {"name": "variable.other.q", "match": BEFORE + NAME + AFTER},
            "operator": {
                "patterns": [
                    {"name": "keyword.operator.iterator.q", "match": r"[/\\']:|':|'|/|\\"},
                    {"name": "keyword.operator.q", "match": r"[-+*%!&|^=<>~,#_$?@.:]"},
                    {"name": "punctuation.separator.statement.q", "match": ";"},
                ],
            },
        },
    }


if __name__ == "__main__":
    print(json.dumps(grammar(), indent=2))
